### ISSUE TITLE
export PYTHONPATH in do_configure_prepend

### ISSUE THREAD

**Issue by rodrigo455** [Geontech/meta-redhawk-sdr#7]
I was working with a custom REDHAWK Component with a redhawk softpkg dependency.
while bitbaking the component... the do_configure step faces the configure.ac line:

**RH_SOFTPKG_CXX([/deps/mylibrary/mylibrary.spd.xml])**

which will check for SDRROOT and run the python script 'redhawk-softpkg'.

In order to get through this step I had to add to my recipe:
**CACHED_CONFIGUREVARS += "ossie_cv_sdr_root=${SDRROOT_STAGED}"**
_(extending CACHED_CONFIGUREVARS of 'redhawk-oeconf.bbclass' to find the spd.xml file)_
do_configure_prepend() {
  export BUILD_SYS=${BUILD_SYS}
  export HOST_SYS=${HOST_SYS}
  export STAGING_INCDIR=${STAGING_INCDIR}
  export STAGING_LIBDIR=${STAGING_LIBDIR}
  export PKG_CONFIG_PATH="${OSSIEHOME_STAGED}/lib/pkgconfig:${PKG_CONFIG_PATH}"
  **export PYTHONPATH=${OSSIEHOME_STAGED}/lib/python:${PYTHONPATH}**
}
_(extendind the PYTHONPATH in do_configure_prepend to import ossie.parsers in 'redhawk-softpkg')_

**Comment by btgoodwin** [comment]
Thank you! I'll try to make this part of the 2.0.6 date I'm working right now (released last Thursday night).

**Comment by btgoodwin** [comment]
@rodrigo455 I'm not going to re-open this in the event it still works in krogoth, but I'm working through support of Poky right now and this fix, specifically the cached config var for SDRROOT, causes components to get "installed" into `image/<staging path>`, and then the packaging misses the files.  Moreover our softpkg dependencies are getting installed in bad locations too... 

I'm working a potentially more flexible fix for this by patching the `redhawk.m4` of `redhawk-core` so that `RH_SOFTPKG_CXX` instead checks for `ossie_cv_sdr_root_target`, which we can then cache instead.  I may backport these fixes to the krogoth branch once finished.

**Comment by rodrigo455** [comment]
I understand.. I had to patch Makefile.am to install things in the correct location.

**Comment by btgoodwin** [comment]
Patches have been added to pyro branch and have been merged to master under tag v2.0.6-1
